version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres_password
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 8080:80
    restart: always
    depends_on:
      - api
      - client
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres_password
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: postgres
    volumes:
      - /app/node_modules
      - ./api:/app
    depends_on:
      - postgres
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
